name: 'terraform-deploy'
on: 
  push:
    branches: [ "none" ]
  workflow_dispatch:
    inputs:
      name:
        description: 'StorageAccount Name'
        required: false
        default: 'Digite um nome aqui'

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_VAR_STORAGE_ACCOUNT_NAME: ${{ github.event.inputs.name}}
    runs-on: ubuntu-latest
    #environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        files: '["**/*.tfvars"]'
    - name: Terraform Init
      run: |
        terraform -chdir=manifest/ init
    - name: Terraform Validate
      run: terraform -chdir=manifest/ validate -no-color
    - name: Terraform Plan
      run: terraform -chdir=manifest/ plan -var-file=var.tfvars -no-color -input=false
      continue-on-error: true
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1
      
    - name: Terraform Apply
      run: terraform -chdir=manifest/ apply -var-file=var.tfvars -auto-approve -no-color -input=false
      continue-on-error: true